# Generated by Django 5.0.7 on 2024-08-31 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0023_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='सेवाको नाम')),
                ('serv_fee', models.IntegerField(verbose_name='सेवा शुल्क')),
                ('serv_time', models.CharField(max_length=50, verbose_name='लाग्ने समय')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='served_services', to='person.section', verbose_name='सम्बन्धित शाखा')),
            ],
        ),
    ]
