# Generated by Django 5.1.1 on 2025-07-21 10:40

import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='सेवाको नाम')),
                ('required_docs', models.TextField(null=True, verbose_name='आवश्यक कागजातहरु')),
                ('serv_fee2', models.CharField(max_length=100, null=True, verbose_name='सेवा शुल्क')),
                ('serv_time', models.CharField(max_length=50, verbose_name='लाग्ने समय')),
                ('sample_documents', models.FileField(null=True, upload_to=services.models.file_upload_to, verbose_name='नमुना कागजातहरु')),
                ('grievence_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='grievences', to='person.post', verbose_name='गुनासो सुन्ने अधिकारी')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='served_services', to='person.section', verbose_name='सम्बन्धित शाखा')),
            ],
        ),
    ]
