# Generated by Django 5.0.7 on 2024-08-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='required_docs',
            field=models.TextField(null=True, verbose_name='आवश्यक कागजातहरु'),
        ),
        migrations.AddField(
            model_name='service',
            name='sample_documents',
            field=models.FileField(null=True, upload_to='', verbose_name='नमुना कागजातहरु'),
        ),
    ]
