# Generated by Django 5.0.7 on 2024-08-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_required_docs_service_sample_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serv_fee2',
            field=models.CharField(max_length=100, null=True, verbose_name='सेवा शुल्क २'),
        ),
    ]
