# Generated by Django 5.0.7 on 2024-09-01 23:27

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_serv_fee2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sample_documents',
            field=models.FileField(null=True, upload_to=services.models.file_upload_to, verbose_name='नमुना कागजातहरु'),
        ),
    ]
