# Generated by Django 5.1.1 on 2024-11-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_sample_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='serv_fee',
        ),
        migrations.AlterField(
            model_name='service',
            name='serv_fee2',
            field=models.CharField(max_length=100, null=True, verbose_name='सेवा शुल्क'),
        ),
    ]
