# Generated by Django 5.1.1 on 2024-11-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0029_employee_profile_image_and_more'),
        ('services', '0005_remove_service_serv_fee_alter_service_serv_fee2'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='grievence_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='grievences', to='person.post', verbose_name='गुनासो सुन्ने अधिकारी'),
        ),
    ]
