# Generated by Django 5.0.7 on 2024-07-29 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'पद', 'verbose_name_plural': 'पदहरु'},
        ),
    ]
