# Generated by Django 5.0.7 on 2024-07-29 02:44

import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_for',
            field=models.IntegerField(choices=person.models.Choices.catagory, default=1),
        ),
    ]
