# Generated by Django 5.0.7 on 2024-07-31 23:17

import django.core.validators
import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_post_post_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='मोबाइल नंबर १० अङ्कको हुनुपर्छ र ९ बाट सुरु भएको', regex='^9[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=100, verbose_name='पदनाम'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_for',
            field=models.IntegerField(choices=person.models.Choices.catagory, default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='publicrepresentative',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='मोबाइल नंबर १० अङ्कको हुनुपर्छ र ९ बाट सुरु भएको', regex='^9[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='publicrepresentative',
            name='ward',
            field=models.IntegerField(choices=person.models.Choices.WardChoices, default=1),
        ),
    ]
