# Generated by Django 5.0.7 on 2024-08-13 01:57

import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_post_post_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nepali_date', nepali_datetime_field.models.NepaliDateField()),
            ],
        ),
    ]
