# Generated by Django 5.0.7 on 2024-08-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_test_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_model',
            name='nepali_date',
        ),
        migrations.AddField(
            model_name='test_model',
            name='year',
            field=models.SmallIntegerField(null=True, verbose_name='वर्ष'),
        ),
    ]
