# Generated by Django 5.0.7 on 2024-08-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_remove_test_model_nepali_date_test_model_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_model',
            name='year',
        ),
    ]
