# Generated by Django 5.0.6 on 2024-08-14 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='_date',
        ),
    ]
