# Generated by Django 5.0.7 on 2024-08-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_rename_date_event__date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='_date',
            new_name='date',
        ),
    ]
