# Generated by Django 5.0.7 on 2024-08-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_rename__date_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='ev_date',
        ),
    ]
