# Generated by Django 5.0.7 on 2024-08-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_rename_date_event_ev_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='str_date',
            field=models.CharField(max_length=15, null=True, verbose_name='कार्यक्रम मिति'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ev_date',
            field=models.DateField(verbose_name='Event_Date'),
        ),
    ]
