# Generated by Django 5.0.7 on 2024-08-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_event_str_date_alter_event_ev_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(max_length=300, null=True, verbose_name='कार्यक्रम स्थान'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(null=True),
        ),
    ]
