# Generated by Django 5.0.7 on 2024-08-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0016_event_event_location_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
