# Generated by Django 5.0.6 on 2024-08-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0017_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
