# Generated by Django 5.0.6 on 2024-08-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0019_event_event_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['weight'], 'verbose_name': 'कर्मचारि', 'verbose_name_plural': 'कर्मचारिहरु'},
        ),
        migrations.AlterModelOptions(
            name='publicrepresentative',
            options={'ordering': ['weight'], 'verbose_name': 'जनप्रतिनिधि', 'verbose_name_plural': 'जनप्रतिनिधिहरु'},
        ),
    ]
