# Generated by Django 5.0.7 on 2024-08-31 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0022_services_subject_committee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
