# Generated by Django 5.0.7 on 2024-09-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0023_delete_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subject_committee',
            new_name='SubjectCommittee',
        ),
    ]
