# Generated by Django 5.0.7 on 2024-09-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0025_publicrepresentative_caninet_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(null=True, verbose_name='लिङ्ग'),
        ),
        migrations.AddField(
            model_name='publicrepresentative',
            name='gender',
            field=models.IntegerField(null=True, verbose_name='लिङ्ग'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='hello@example.com', max_length=254, null=True, verbose_name='ईमेल'),
        ),
        migrations.AlterField(
            model_name='publicrepresentative',
            name='email',
            field=models.EmailField(default='hello@example.com', max_length=254, null=True, verbose_name='ईमेल'),
        ),
    ]
