# Generated by Django 5.0.7 on 2024-09-02 03:13

import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0026_employee_gender_publicrepresentative_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicrepresentative',
            old_name='caninet_member',
            new_name='cabinet_member',
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(choices=person.models.Choices.male_female_choices, default=1, null=True, verbose_name='लिङ्ग'),
        ),
        migrations.AlterField(
            model_name='publicrepresentative',
            name='gender',
            field=models.IntegerField(choices=person.models.Choices.male_female_choices, default=1, null=True, verbose_name='लिङ्ग'),
        ),
    ]
