# Generated by Django 5.0.7 on 2024-09-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0027_rename_caninet_member_publicrepresentative_cabinet_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectcommittee',
            options={'ordering': ['coordinator'], 'verbose_name': 'विषयगत समिति', 'verbose_name_plural': 'विषयगत समितिहरु'},
        ),
        migrations.AlterField(
            model_name='subjectcommittee',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='involved_committees', to='person.publicrepresentative', verbose_name='सदस्य हरु'),
        ),
    ]
