# Generated by Django 5.1.1 on 2024-11-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0028_alter_subjectcommittee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='publicrepresentative',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
